# accounts/constants.py

BANK_CHOICES = [
    ('', '--- Select Your Bank ---'),
    ('044', 'Access Bank'),
    ('063', 'Access Bank (Diamond)'),
    ('050', 'Ecobank Nigeria'),
    ('070', 'Fidelity Bank'),
    ('011', 'First Bank of Nigeria'),
    ('214', 'First City Monument Bank (FCMB)'),
    ('058', 'Guaranty Trust Bank (GTB)'),
    ('301', 'Jaiz Bank'),
    ('082', 'Keystone Bank'),
    ('303', 'Lotus Bank'),
    ('999991', 'PalmPay'),
    ('076', 'Polaris Bank'),
    ('101', 'Providus Bank'),
    ('221', 'Stanbic IBTC Bank'),
    ('068', 'Standard Chartered Bank'),
    ('232', 'Sterling Bank'),
    ('302', 'TAJ Bank'),
    ('032', 'Union Bank of Nigeria'),
    ('033', 'United Bank for Africa (UBA)'),
    ('215', 'Unity Bank'),
    ('035', 'Wema Bank'),
    ('057', 'Zenith Bank'),
    ('50211', 'Kuda Bank'),
    ('999992', 'OPay (Paycom)'),
]