# Generated by Django 5.0.1 on 2026-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_approved_alter_user_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='news/')),
                ('tiktok_url', models.URLField(blank=True, help_text='Paste TikTok video link here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
