# Generated by Django 5.0.1 on 2026-02-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_newsupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsupdate',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsupdate',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
