# Generated by Django 5.0.1 on 2026-02-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_newsupdate_options_newsupdate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsupdate',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
