# Generated by Django 5.0.1 on 2026-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_newsupdate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, help_text='Verified name from Bank', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('044', 'Access Bank'), ('011', 'First Bank of Nigeria'), ('058', 'GTBank'), ('057', 'Zenith Bank'), ('033', 'United Bank for Africa (UBA)'), ('050', 'EcoBank'), ('070', 'Fidelity Bank'), ('030', 'Heritage Bank'), ('082', 'Keystone Bank'), ('076', 'Polaris Bank'), ('232', 'Sterling Bank'), ('032', 'Union Bank'), ('215', 'Unity Bank'), ('035', 'Wema Bank'), ('068', 'Standard Chartered'), ('214', 'First City Monument Bank (FCMB)'), ('50515', 'Moniepoint MFB'), ('999992', 'OPay'), ('999991', 'PalmPay'), ('50211', 'Kuda Bank')], max_length=10, null=True),
        ),
    ]
