# Generated by Django 5.0.1 on 2026-02-13 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_account_name_user_account_number_user_bank_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsupdate',
            name='content',
        ),
        migrations.AddField(
            model_name='videopost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='newsupdate',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
