# Generated by Django 5.0.1 on 2026-02-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_newsupdate_content_videopost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
