# Generated by Django 5.2.11 on 2026-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_disciplinaryreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="bank_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
