# Generated by Django 5.2.11 on 2026-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_disbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipient_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="sender_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
