# Generated by Django 5.2.11 on 2026-02-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_message_recipient_deleted_message_sender_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.organizationunit",
            ),
        ),
    ]
