# Generated by Django 5.2.11 on 2026-02-26 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_announcement_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="NewsUpdate",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bank_code",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="education",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="user",
            name="course_of_study",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Primary"),
                    ("secondary", "Secondary/SSCE"),
                    ("tertiary", "College/NCE"),
                    ("polytechnics", "Certificate/ND"),
                    ("undergraduate", "Undergraduate"),
                    ("graduate", "Graduate (BSc/HND)"),
                    ("postgraduate", "Postgraduate (MSc/PhD)"),
                    ("specialized", "Specialized/Technical"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_graduated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payrollrecord",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bank_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("044", "Access Bank"),
                    ("011", "First Bank"),
                    ("058", "GTBank"),
                    ("057", "Zenith Bank"),
                    ("033", "UBA"),
                    ("050", "EcoBank"),
                    ("50515", "Moniepoint MFB"),
                    ("999992", "OPay"),
                    ("999991", "PalmPay"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lga",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lgas",
                to="accounts.state",
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="lga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wards",
                to="accounts.lga",
            ),
        ),
        migrations.AddField(
            model_name="organizationunit",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="accounts.ward",
            ),
        ),
    ]
