# Generated by Django 5.2.11 on 2026-02-26 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_lga_state_ward_delete_newsupdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationunit",
            name="lga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.lga",
            ),
        ),
        migrations.AddField(
            model_name="organizationunit",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.state",
            ),
        ),
        migrations.AlterField(
            model_name="organizationunit",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.ward",
            ),
        ),
    ]
