# Generated by Django 5.2.11 on 2026-02-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_organizationunit_lga_organizationunit_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationunit",
            name="ward",
        ),
        migrations.AddField(
            model_name="organizationunit",
            name="ward_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
