# Generated by Django 5.2.11 on 2026-02-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_organizationunit_ward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="course_of_study",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="education_level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="graduation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
